# TransformerLM Resource Accounting

## FLOPS Accounting

## Memory Accounting

## Quick Start

Make sure to run this notebook within the uv environment. You can start it with:
```bash
uv run jupyter lab playground.ipynb
```


In [5]:
# Import basic modules to verify environment
import sys
import torch
import math
import numpy as np
import torch.nn as nn

print(f"Python: {sys.version}")
print(f"PyTorch: {torch.__version__}")
print(f"NumPy: {np.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")


Python: 3.13.5 (main, Jul  8 2025, 20:55:53) [Clang 20.1.4 ]
PyTorch: 2.6.0
NumPy: 2.3.2
CUDA available: False


In [18]:
# Load the Transformer to verify calculations
from cs336_basics.transformer import TransformerLM, TransformerBlock
import typing

vocab_size = 10000
context_length = 256
d_model = 512
d_ff = 1344
theta = 10000
num_layers = 4
num_heads = 16

transformer = TransformerLM(vocab_size, d_model, context_length, num_layers, num_heads, d_ff, theta)

def print_memory_stats(params, expected_param_count):
    print(f"Calculated memory (parameter count): {expected_param_count}")
    print(f"Actual memory (parameter count): {params.numel()}")
    print(f"Parameter type: {params.dtype} size: {params.element_size()}")
    print(f"Total size: {(params.numel() * params.element_size())/1024/1024.0:.2f} MB")

### Embedding Layer: 
#### Memory: O(vocab_size * d_model) 
#### FLOPS: None
We will have an embedding vector for every token in the vocabulary
Total memory: O(vocab_size * d_model)

In [19]:
embed_params = transformer.embedding.embeddings
print_memory_stats(embed_params, vocab_size * d_model)

Calculated memory (parameter count): 5120000
Actual memory (parameter count): 5120000
Parameter type: torch.float32 size: 4
Total size: 19.53 MB


In [20]:
rms_norm_parms = typing.cast(TransformerBlock, transformer.transformer_blocks[0]).pre_mha_norm.gain
print_memory_stats(rms_norm_parms, d_model)

Calculated memory (parameter count): 512
Actual memory (parameter count): 512
Parameter type: torch.float32 size: 4
Total size: 0.00 MB


In [26]:
attn_proj_params = typing.cast(TransformerBlock, transformer.transformer_blocks[0]).mha.attention_weights.weight
print("Multi-Head Attention Projection Weights\n")
print_memory_stats(attn_proj_params, 3 * d_model * d_model)

print("\nMulti-Head Attention Output Weights\n")
attn_out_params = typing.cast(TransformerBlock, transformer.transformer_blocks[0]).mha.output_weights.weight
print_memory_stats(attn_out_params, d_model * d_model)

ff_linear1_params = typing.cast(TransformerBlock, transformer.transformer_blocks[0]).ff.linear1.weight
ff_linear2_params = typing.cast(TransformerBlock, transformer.transformer_blocks[0]).ff.linear2.weight
ff_linear3_params = typing.cast(TransformerBlock, transformer.transformer_blocks[0]).ff.linear3.weight

print("\nSwiGLU weights L1, L2, L3\n")
print_memory_stats(ff_linear1_params, d_model * d_ff)
print_memory_stats(ff_linear2_params, d_model * d_ff)
print_memory_stats(ff_linear3_params, d_model * d_ff)


Multi-Head Attention Projection Weights

Calculated memory (parameter count): 786432
Actual memory (parameter count): 786432
Parameter type: torch.float32 size: 4
Total size: 3.00 MB

Multi-Head Attention Output Weights

Calculated memory (parameter count): 262144
Actual memory (parameter count): 262144
Parameter type: torch.float32 size: 4
Total size: 1.00 MB

SwiGLU weights L1, L2, L3

Calculated memory (parameter count): 688128
Actual memory (parameter count): 688128
Parameter type: torch.float32 size: 4
Total size: 2.62 MB
Calculated memory (parameter count): 688128
Actual memory (parameter count): 688128
Parameter type: torch.float32 size: 4
Total size: 2.62 MB
Calculated memory (parameter count): 688128
Actual memory (parameter count): 688128
Parameter type: torch.float32 size: 4
Total size: 2.62 MB


In [ ]:
output_proj_params = 

In [52]:
class RotaryPositionalEmbedding(nn.Module):
    def __init__(self, theta: float, d_k: int, max_seq_len: int, device: torch.device | None = None):
        super().__init__()
        rotation_matrices = []
        dtype = torch.float32
        for i in range(max_seq_len):
            rotation_values = torch.tensor([i / (math.pow(theta, (2 * (k // 2)) / float(d_k))) for k in range(d_k)], dtype=dtype)
            print(rotation_values)
            cos_values = torch.cos(rotation_values)
            mask = torch.arange(rotation_values.shape[0], dtype=dtype) % 2 == 0
            sin_values = torch.sin(torch.where(mask, rotation_values, 0))[:-1]
            rotation_matrices.append(torch.diag(cos_values) + torch.diag(sin_values, diagonal=-1) + torch.diag(-sin_values, diagonal=1))
        self.register_buffer('rotary_matrix', torch.stack(rotation_matrices, dim=0).to(device))
    
    def forward(self, x: torch.Tensor, token_positions: torch.Tensor) -> torch.Tensor:
        rotary_matrices = self.rotary_matrix[token_positions]
        return einsum(rotary_matrices, x, '... seq_len d_k d_k, ... seq_len d_k -> ... seq_len d_k')

In [54]:
rope = RotaryPositionalEmbedding(2, 6, 2)
rope.rotary_matrix

tensor([0., 0., 0., 0., 0., 0.])
tensor([1.0000, 1.0000, 0.7937, 0.7937, 0.6300, 0.6300])


TypeError: RotaryPositionalEmbedding.forward() missing 1 required positional argument: 'token_positions'

In [48]:
class RotaryPositionalEmbeddingCorrect(nn.Module):
    def __init__(self, theta: float, d_k: int, max_seq_len: int, device: torch.device | None = None):
        super().__init__()
        dtype = torch.float32

        # positions: [0, 1, ..., max_seq_len-1]
        positions = torch.arange(max_seq_len, device=device, dtype=dtype).unsqueeze(1)

        # pair indices: [0, 1, ..., d_k/2 - 1]
        pair_indices = torch.arange(0, d_k // 2, device=device, dtype=dtype)

        # inverse frequencies theta^{-2i/d_k}
        inv_freq = theta ** (-2.0 * pair_indices / float(d_k))
        

        # angles = position * inv_freq  -> shape: (max_seq_len, d_k/2)
        angles = positions * inv_freq
        print(angles)
        cos = torch.cos(angles)
        sin = torch.sin(angles)

        # Cache trig tables per position for each pair
        self.register_buffer('cos_table', cos)
        self.register_buffer('sin_table', sin)
        
    def forward(self, x: torch.Tensor, token_positions: torch.Tensor) -> torch.Tensor:
        # Fetch per-position cos/sin for each feature pair
        cos_table_t = cast(torch.Tensor, self.cos_table)
        sin_table_t = cast(torch.Tensor, self.sin_table)
        cos = cos_table_t[token_positions].to(dtype=x.dtype)
        sin = sin_table_t[token_positions].to(dtype=x.dtype)

        x_even = x[..., 0::2]
        x_odd = x[..., 1::2]

        rotated_even = x_even * cos - x_odd * sin
        rotated_odd = x_even * sin + x_odd * cos

        # Interleave even/odd back into last dimension
        out = torch.empty_like(x)
        out[..., 0::2] = rotated_even
        out[..., 1::2] = rotated_odd
        return out

In [7]:
# torch.unsqeeze
torch.arange(5).unsqueeze(0)

torch.Size([1, 5])

In [9]:
# torch.outer
d_k = 10
theta = 1000
max_seq_len = 5
inv_freq = theta ** (-torch.arange(0, d_k, 2) / d_k)
positions = torch.arange(0, max_seq_len)
print(inv_freq)
print(positions)
torch.outer(positions, inv_freq)

tensor([1.0000, 0.2512, 0.0631, 0.0158, 0.0040])
tensor([0, 1, 2, 3, 4])


tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 2.5119e-01, 6.3096e-02, 1.5849e-02, 3.9811e-03],
        [2.0000e+00, 5.0238e-01, 1.2619e-01, 3.1698e-02, 7.9621e-03],
        [3.0000e+00, 7.5357e-01, 1.8929e-01, 4.7547e-02, 1.1943e-02],
        [4.0000e+00, 1.0048e+00, 2.5238e-01, 6.3396e-02, 1.5924e-02]])

In [13]:
# torch.repeat_interleave
dim1 = torch.arange(5)
dim2 = torch.arange(6)
matrix = torch.outer(dim1, dim2)
matrix.repeat_interleave(2, dim=-1)

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5],
        [ 0,  0,  2,  2,  4,  4,  6,  6,  8,  8, 10, 10],
        [ 0,  0,  3,  3,  6,  6,  9,  9, 12, 12, 15, 15],
        [ 0,  0,  4,  4,  8,  8, 12, 12, 16, 16, 20, 20]])

In [19]:
# torch.gather
a = torch.arange(5).unsqueeze(-1)
dim1 = torch.arange(5)
dim2 = torch.arange(6)
b = torch.outer(dim1, dim2)
print(a)
print(b)
torch.gather(b, -1, a)

tensor([[0],
        [1],
        [2],
        [3],
        [4]])
tensor([[ 0,  0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4,  5],
        [ 0,  2,  4,  6,  8, 10],
        [ 0,  3,  6,  9, 12, 15],
        [ 0,  4,  8, 12, 16, 20]])


tensor([[ 0],
        [ 1],
        [ 4],
        [ 9],
        [16]])

In [ ]:
# TODO: Advanced Indexing